// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuzxwF_UdWKn8bJwrXcwVbHLcly_bRY8k',
    appId: '1:8394062866:web:6dde5398f2c6b38b126ccb',
    messagingSenderId: '8394062866',
    projectId: 'petmate-c58b3',
    authDomain: 'petmate-c58b3.firebaseapp.com',
    storageBucket: 'petmate-c58b3.firebasestorage.app',
    measurementId: 'G-VSJCSCXGKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaMktY79msokiOWEwww08eu9zk9wlT80k',
    appId: '1:8394062866:android:e6bbe1ec77c1ba73126ccb',
    messagingSenderId: '8394062866',
    projectId: 'petmate-c58b3',
    storageBucket: 'petmate-c58b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7399OJWkLTzhVTOI4zuwKhiDqWQOkFoY',
    appId: '1:8394062866:ios:bdee9fc4d9acb7ce126ccb',
    messagingSenderId: '8394062866',
    projectId: 'petmate-c58b3',
    storageBucket: 'petmate-c58b3.firebasestorage.app',
    iosBundleId: 'com.example.petmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7399OJWkLTzhVTOI4zuwKhiDqWQOkFoY',
    appId: '1:8394062866:ios:bdee9fc4d9acb7ce126ccb',
    messagingSenderId: '8394062866',
    projectId: 'petmate-c58b3',
    storageBucket: 'petmate-c58b3.firebasestorage.app',
    iosBundleId: 'com.example.petmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuzxwF_UdWKn8bJwrXcwVbHLcly_bRY8k',
    appId: '1:8394062866:web:67a8fa4e60ee894f126ccb',
    messagingSenderId: '8394062866',
    projectId: 'petmate-c58b3',
    authDomain: 'petmate-c58b3.firebaseapp.com',
    storageBucket: 'petmate-c58b3.firebasestorage.app',
    measurementId: 'G-TFPKKNB8LX',
  );
}
